import { Vehicle, Location, Reservation } from '../types';

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: 'loc-1',
    name: 'Tlemcen Centre-Ville',
    city: 'Tlemcen',
    fee: 0,
    active: true,
  },
  {
    id: 'loc-2',
    name: 'Aéroport Messali Hadj Tlemcen (Zenata)',
    city: 'Tlemcen',
    fee: 0,
    active: true,
  },
  {
    id: 'loc-3',
    name: 'Gare Routière Tlemcen',
    city: 'Tlemcen',
    fee: 0,
    active: true,
  },
  {
    id: 'loc-4',
    name: 'Livraison à Domicile (Grand Tlemcen)',
    city: 'Tlemcen',
    fee: 1500,
    active: true,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-clio-5',
    name: 'Renault Clio 5 Life',
    brand: 'Renault',
    category: 'Citadine',
    transmission: 'Manuelle',
    fuel: 'Essence',
    seats: 5,
    pricePerDay: 7000,
    imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    features: ['Climatisation', 'Bluetooth / USB', 'Régulateur de vitesse', 'Direction assistée', 'Fixations Isofix'],
    available: true,
    year: 2023,
    plateNumber: '13-12456-123',
  },
  {
    id: 'veh-stepway',
    name: 'Dacia Sandero Stepway Techroad',
    brand: 'Dacia',
    category: 'Citadine',
    transmission: 'Automatique',
    fuel: 'Essence',
    seats: 5,
    pricePerDay: 8500,
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    features: ['Écran Tactile GPS', 'Caméra de recul', 'Climatisation auto', 'Barres de toit', 'Mode Eco'],
    available: true,
    year: 2024,
    plateNumber: '13-25890-124',
  },
  {
    id: 'veh-accent',
    name: 'Hyundai Accent RB',
    brand: 'Hyundai',
    category: 'Berline',
    transmission: 'Automatique',
    fuel: 'Essence',
    seats: 5,
    pricePerDay: 9000,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    features: ['Boîte Automatique', 'Grand Coffre 465L', 'Climatisation', 'Commandes au volant', 'Antibrouillards'],
    available: true,
    year: 2023,
    plateNumber: '13-33412-123',
  },
  {
    id: 'veh-golf-8',
    name: 'Volkswagen Golf 8 R-Line',
    brand: 'Volkswagen',
    category: 'Berline',
    transmission: 'Automatique',
    fuel: 'Diesel',
    seats: 5,
    pricePerDay: 14000,
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    features: ['Cockpit Digital', 'Pack R-Line', 'Phares LED Matrix', 'Apple CarPlay sans fil', 'Aide au stationnement'],
    available: true,
    year: 2023,
    plateNumber: '13-44109-123',
  },
  {
    id: 'veh-peugeot-208',
    name: 'Peugeot 208 Allure',
    brand: 'Peugeot',
    category: 'Citadine',
    transmission: 'Automatique',
    fuel: 'Essence',
    seats: 5,
    pricePerDay: 9500,
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
    features: ['i-Cockpit 3D', 'Jantes alu 16"', 'Climatisation auto', 'Radar arrière', 'Démarrage sans clé'],
    available: true,
    year: 2023,
    plateNumber: '13-55912-123',
  },
  {
    id: 'veh-tucson',
    name: 'Hyundai Tucson N-Line',
    brand: 'Hyundai',
    category: 'SUV',
    transmission: 'Automatique',
    fuel: 'Diesel',
    seats: 5,
    pricePerDay: 18000,
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
    features: ['Toit Ouvrant Panoramique', 'Transmission 4x4 HTRAC', 'Sièges Chauffants', 'Caméra 360°', 'Audio Premium'],
    available: true,
    year: 2024,
    plateNumber: '13-67891-124',
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-demo-1',
    vehicleId: 'veh-clio-5',
    customerName: 'Karim Benali',
    customerPhone: '0555 12 34 56',
    customerEmail: 'karim.benali@example.com',
    pickupLocation: 'Aéroport Messali Hadj Tlemcen (Zenata)',
    returnLocation: 'Aéroport Messali Hadj Tlemcen (Zenata)',
    startDate: '2026-09-24T10:00:00.000Z',
    endDate: '2026-09-27T10:00:00.000Z',
    totalDays: 3,
    totalPrice: 21000,
    status: 'CONFIRMED',
    notes: 'Vol en provenance de Paris Orly à 09h30.',
    createdAt: '2026-09-22T14:30:00.000Z',
  },
  {
    id: 'res-demo-2',
    vehicleId: 'veh-accent',
    customerName: 'Amine Mansouri',
    customerPhone: '0661 98 76 54',
    customerEmail: 'amine.m@example.com',
    pickupLocation: 'Tlemcen Centre-Ville',
    returnLocation: 'Tlemcen Centre-Ville',
    startDate: '2026-09-25T14:00:00.000Z',
    endDate: '2026-09-30T14:00:00.000Z',
    totalDays: 5,
    totalPrice: 45000,
    status: 'PENDING',
    notes: 'Paiement à la livraison.',
    createdAt: '2026-09-23T08:15:00.000Z',
  },
];
